image: node:23.6.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - frontend/package-lock.json
      prefix: npm
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm install
    - npm run build
    - cp -a dist/. ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"